#!/usr/bin/env bash
#
# Copyright Bruno Costa @ iBET 16/02/2017
#
# Write_report.sh
# Writes a multi-part MD report.
#
# call as [first_] [lib_last] [type]

# Types are {"header","fastq","fasta","filtering","genome","end"}

LIB_FIRST=$1
LIB_LAST=$2
TYPE=$3

#  Fastq
#    - Fastqc (For now just this one)
#      Per base sequence quality
#      *Per sequence GC content
#      *Adapter Content
#       
#  Trimming
#    - Detailed Log (Table?)
#  Fasta
#    - Size profiles
#      One graph per lib. 
#      Possible pair-wise comparison depending on lib number. (I think two at most)
#  Filtering
#    - Detailed report of filtering (Grab that log and build table)
#  Genome
#    - (How low details not sure has spot)
#  End
#    - Stats per lib (for each )
#    - Counts per lib. (Issues with matrix size. Needs to be sized)


#Gets the script directory
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#Get config settings
. $DIR/"config/workdirs.cfg"

mkdir -p ${workdir}"count/images"
log_file=$workdir"log/"$(date +"%y|%m|%d-%H:%M:%S")":PPID${PPID}:write_report:$1-$2.log"
echo $(date +"%y/%m/%d-%H:%M:%S")" - "$(basename ${log_file}) 
exec 2>&1 >> ${log_file}

SCRIPT_DIR=$DIR"/scripts"
OUTPUT_FILE=${workdir}count/miRPursuit_REPORT-Run${PPID}.tex


if [[ "${TYPE}" == "header" ]]; then
	printf "\\\documentclass{article}
\\\title{miRPursuit - REPORT}
\\\author{miRPursuit - Forest-BiotechLab}
\\\usepackage{graphicx}
\\\graphicspath{ {${workdir}count/images/} }
\\\begin{document}
	\\\maketitle
	Hello world
	\\\pagebreak
	\\\tableofcontents
	\\\pagebreak\n" > $OUTPUT_FILE

	printf "\t\\\section{Introduction}\n\tThis report was automatically generated by miRPursuit. The genome used was ${GENOME}\n" >> ${OUTPUT_FILE}
fi

if [[ "${TYPE}" == "fasta" ]]; then
	printf "\t\\\section{Profile}
	Something about this section\n" >> $OUTPUT_FILE


	#Choses run mode based on input arguments
	cycle=$(eval echo {${LIB_FIRST}..${LIB_LAST}})
	printf $(date +"%y/%m/%d-%H:%M:%S")" - Copying all fasta files to workdir\n"
	for i in $cycle
	do
	  LIB_NOW=$i
	  LIB=$(printf "%02d\n"  $LIB_NOW)  
	  $SCRIPT_DIR/size_fasta.py --input ${workdir}data/fasta/Lib${LIB}.fa --output ${workdir}count/Lib${LIB}-profile.tsv
	  $SCRIPT_DIR/graph_sizedistr.R ${workdir}count/Lib${LIB}-profile.tsv ${workdir}count/images/
	  #convert image Add image
	printf "
	\\\begin{figure}[h]
	\\\centering
	\\\includegraphics[width=8cm, height=8cm]{barplot-Lib${LIB}-size-distr}
	\\\caption{this is the caption of the picture above}
	\\\label{fig:profile${LIB}}
	\\\end{figure}\n" >> ${OUTPUT_FILE}



	done

	##Write to tex

fi



if [[ "${TYPE}" == "end" ]]; then

	printf "\\\end{document}\n" >> ${OUTPUT_FILE}

fi